project:
  type: website

website:
  title: "Nine Springs Neighborhood"
  site-url: https://myelinviolin.quarto.pub/ninesprings/
  description: "Local neighborhood news, events, and resources for the Nine Springs Neighborhood on the south side of Madison, WI"

  navbar:
    background: primary
    left: 
      - blogpostlist.qmd
      - localbusinesses.qmd
      - resources.qmd
      - events.qmd
      - iNat.qmd

    right:
      - about.qmd
format:
  html:
    theme: litera
    css: styles.css

editor: visual

execute: 
  freeze: auto

