project:
  type: website

website:
  title: "Nine Springs Neighborhood"

  navbar:
    background: primary
    left: 
      - blogpostlist.qmd
      - localbusinesses.qmd
      - resources.qmd
      - events.qmd
      - iNat.qmd

    right:
      - about.qmd
format:
  html:
    theme: litera
    css: styles.css

editor: visual

